### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by dsteinel** [jeremyben/nunjucks-cli#1]
Hey,

I'd like to use nunjucks with npm. So I installed nunjucks with:
`npm i -g nunjucks-cli`
If I try to run nunjucks from commandline with:
`nunjucks index.html` or just `nunjucks`
I get this error:
`env: node\r: No such file or directory`

Has someone the same issue?

I am running on OSX 10.11.4

**Comment by dsteinel** [comment]
I found a solution here: 
[here](http://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo)

`
brew install dos2unix
`
`
sudo dos2unix /usr/local/lib/node_modules/task-app/src/task-app.js
`

**Comment by jeremyben** [comment]
It seems to be due to the CLRF endlines, as I created the module on Windows. I'll take car of it.

**Comment by jeremyben** [comment]
There you go. Thanks for the heads up.

**Comment by klardotsh** [comment]
I still have this issue on Arch Linux

**Comment by jeremyben** [comment]
Ok I think I fixed it, tested on Ubuntu and correction worked.
Could you give me a hint ?

**Comment by klardotsh** [comment]
Confirmed fixed as of the latest version on NPM.

**Comment by klardotsh** [comment]
Thanks!

**Comment by alexandercurtis** [comment]
Hi, I just pulled version 0.5.0 on Linux and still seeing line ending problems:

    sudo npm install --global nunjucks-cli
    /usr/bin/nunjucks -> /usr/lib/node_modules/nunjucks-cli/index.js
    /usr/lib
    └── nunjucks-cli@0.5.0 

    file -L /usr/bin/nunjucks
    /usr/bin/nunjucks: a /usr/bin/env node\015 script, ASCII text executable, with CRLF line terminators

**Comment by jeremyben** [comment]
Yep sorry, I'm gonna set gitattributes to eol=LF to fix this once and for all.

**Comment by jeremyben** [comment]
Could you check again with 0.5.1 ?

**Comment by alexandercurtis** [comment]
@jeremyben Yep, that's working fine. Thanks!
